Fix site responsiveness
abanseka/landing-page pull request #2
Opened 2021-11-06 23:08 UTC by abanseka

2021-11-07 15:55 UTC, abanseka commented
fix reponsiveness

2021-11-08 11:18 UTC, ahamad-ch commented on src/Components/Contents/.prettierrc
> +}
You just need one prettier file. Not on all the folders. So find a solution for making it with a single file.

2021-11-08 11:20 UTC, ahamad-ch commented on src/Components/Contents/Contents.js
> +import "./Contents.css";
make the css import at the end of all imports.

2021-11-08 11:21 UTC, ahamad-ch commented on src/Components/Cta/Cta.css
> +.text button {
Here instead of applying css for the element apply it to a classname.

2021-11-08 11:22 UTC, ahamad-ch commented on src/Components/Cta/Cta.js
> +          <button className="btn">Try For Free</button>
Instead of going for a basic class name, go for a detailed class name which makes it more meaningful

2021-11-08 11:25 UTC, ahamad-ch commented on src/Components/Features/Features.css
> +@media (max-width: 1360px) {
Here, instead of choosing a random screen width you can go for default screen resolutions

```
@media only screen and (max-width: 600px) {...}

/* Small devices (portrait tablets and large phones, 600px and up) */
@media only screen and (min-width: 600px) {...}

/* Medium devices (landscape tablets, 768px and up) */
@media only screen and (min-width: 768px) {...}

/* Large devices (laptops/desktops, 992px and up) */
@media only screen and (min-width: 992px) {...}

/* Extra large devices (large laptops and desktops, 1200px and up) */
@media only screen and (min-width: 1200px) {...}
```

2021-11-08 11:39 UTC, ahamad-ch commented on src/Components/Header/Header.js
>  // import screenImage3 from './images/header images/screenImage3.png'
Use the imports like `../../images/header/screenImage2.png`
So it needs to go to that specific folder.
And also remove the `imagePlaceholder`

2021-11-08 11:40 UTC, ahamad-ch requested changes
Also try to fix the horizontal scrollbar which is not intented to be there.

2021-11-09 11:45 UTC, ahamad-ch approved these changes

2021-11-09 11:46 UTC, merged