- Hamburger menu implementation …
abanseka/landing-page pull request #4
Opened 2021-11-11 20:34 UTC by abanseka

Implement Hamburger Menu on Responsive design 

<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>

2021-11-12 18:10 UTC, ahamad-ch commented on public/style.css
> +  body p {
Always apply css to specific classnames

2021-11-17 17:25 UTC, abanseka commented on public/style.css
> +  body p {
Resolved

2021-11-30 06:43 UTC, ahamad-ch requested changes

2021-12-22 12:18 UTC, ahamad-ch commented on src/Components/Header/Header.js
> +        <ul className={`header-menu ${isMenuOpen ? "open" : ""}`}>
I can suggest you to use the `classnames` package which will make it simple here.

2021-12-23 13:20 UTC, ahamad-ch commented on src/Components/Header/Header.js
> +        className={`btn-container ${classNames("isElementVisble", {
Is there a need for the className "isElementVisible"?

2021-12-23 13:20 UTC, ahamad-ch commented on src/Components/Header/Header.css
> +    margin-top: -50vh;
I think this is not yet addressed.

2021-12-27 11:41 UTC, ahamad-ch approved these changes

2021-12-27 11:41 UTC, merged