Added Cursor pointer on menu and link hover
abanseka/landing-page pull request #6
Opened 2021-12-28 05:38 UTC by abanseka

2021-12-28 05:44 UTC, abanseka commented on src/Components/Header/Header.css
> +    height: 50vh;
The nav links overlapped the hamburger-menu-button
making it difficult to be clicked. 
> reason for added height.

2021-12-29 07:55 UTC, ahamad-ch commented
Next time when you're starting to work on something new, make sure you create a new branch and then add a PR.

2021-12-29 08:03 UTC, ahamad-ch requested changes

2021-12-29 08:03 UTC, ahamad-ch commented on src/Components/Footer/Footer.js
> +              </scroll.Link>
You can import `{ Link} from "react-scroll"` and then use `<Link to="gallery" smooth={true}>`

2021-12-29 09:05 UTC, ahamad-ch commented on src/Components/Footer/Footer.js
> +            </p>
As the links looks a bit expanded now, lets add the links inside a loop.
You can use a variable with the values needed.
Example:
```
const links = [{
  label: "Home",
  to: "features"
}, {
  label: "About",
  to: "partners"
}]
```

2021-12-29 10:55 UTC, ahamad-ch approved these changes

2021-12-29 10:55 UTC, merged